spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.127.185:8848
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu
        - id: qq_route
          uri: https://www.qq.com/
          predicates:
            - Query=url, qq
        - id: admin_route
          uri: lb://renren-fast            # lb 负载均衡
          predicates:
            - Path=/api/**                 # 所有api请求路径到这里来
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}   # 将api路径过滤成renren-fast

  application:
    name: mall-gateway
server:
  port: 88