spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        -id: baidu # 路由id值
        uri: www.baidu.com # 需要跳转到的位置
        predicates:
          -Query=url,baidu     # 匹配Url中存在baidu 则 跳转到 uri
  application:
    name: mall-gateway
server:
  port: 88